language: c
compiler: gcc

#env:
  #global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   #- secure: ""

addons:
  coverity_scan:
    project:
      name: "SV_SK"
      description: ""
    build_command_prepend: ""
    build_command:   "make"
    branch_pattern: "master"

script: make
